name: flutter_grate_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  progress_dialog: ^1.2.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  modal_progress_hud: ^0.1.3
  sqflite: ^1.1.3
  path_provider: ^0.4.1
  flushbar: ^1.9.1
  material_design_icons_flutter: 3.4.4595
  uuid: ^2.0.4
  smooth_star_rating: 1.0.3
  shimmer: ^1.0.1
  flutter_colorpicker: any
  intl: ^0.16.0
  painter: ^0.3.2
  popup_menu: ^1.0.4
  flutter_typeahead: ^1.7.0
  video_player:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Monserrat
      fonts:
        - asset: fonts/font_bold.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/font_regular.ttf
          weight: 700