name: flutter_grate_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  http:
  sqflite:
  path_provider:
  flushbar: ^1.10.0
  material_design_icons_flutter:
  uuid:
  smooth_star_rating:
  shimmer:
  flutter_colorpicker:
  intl:
  painter:
  cached_network_image:
  flutter_typeahead:
  connectivity:
  video_player:
  image_picker:
  async:
  dotted_border:
  flutter_html:
  url_launcher:
  youtube_player_flutter:
  flutter_keyboard_visibility:
  flutter_fullpdfview:
  hive:
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Monserrat
      fonts:
        - asset: fonts/font_bold.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/font_regular.ttf
          weight: 700