name: flutter_grate_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  progress_dialog: ^1.2.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  modal_progress_hud: ^0.1.3
  sqflite: ^1.1.3
  path_provider:
  flushbar:
  material_design_icons_flutter:
  uuid:
  smooth_star_rating:
  shimmer:
  flutter_colorpicker: any
  intl:
  painter:
  popup_menu:
  flutter_typeahead:
  connectivity: ^0.4.6+2
  video_player:
  image_picker:
  async:
  dotted_border:
  flutter_html:
  url_launcher:
  flutter_pdfview:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Monserrat
      fonts:
        - asset: fonts/font_bold.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/font_regular.ttf
          weight: 700